### PR TITLE
feat: add a data preview panel in the editor

### LINKED ISSUE #144: Add a data table in the editor

### PR DESCRIPTION
**Pull request by sehilyi**
Fix #144 

Screen Shot 2021-02-03 at 10 25 40 PM

### CODE REVIEW

**Comment by sehilyi** [comment]
@wangqianwen0418 Can you review whether a newly add data preview panel properly works in your computer and as you expected?

**Comment by wangqianwen0418** [comment]
@sehilyi , the data table looks great!
I only have a few small comments 
- Maybe we can change from "tileset" to "bed",  "vector", or "multivec"?
- do you think we can also specify the tracks using the data? something like a track id
- Sometimes, the data table has no data. The problem is resolved after refreshing the page. I am not sure whether this is caused by the internet connection or my computer memory
- maybe adding a visual cue to tell people about the existence of this table?

**Comment by sehilyi** [comment]
@wangqianwen0418 Thank you for reviewing this and sharing feedback, this is very helpful!

> Maybe we can change from "tileset" to "bed", "vector", or "multivec"?

This is a good suggestion, I will update this!

> do you think we can also specify the tracks using the data? something like a track id

We can specify the `track id`, but it will be unreadable and arbitrary strings. I think allowing users to easily map between individual tracks and data table would be really useful, but it would take some more time to implement. I will add this as a separate issue.

> Sometimes, the data table has no data. The problem is resolved after refreshing the page. I am not sure whether this is caused by the internet connection or my computer memory

This is odd, I will investigate more.

> maybe adding a visual cue to tell people about the existence of this table?

Good idea, perhaps we can put a hidden (green) circle by the title (i.e., "Data Preview") and show it when data is being updated. Or, do you have any suggestion?

**Comment by wangqianwen0418** [comment]
image

Not sure whether missing value in the table is related to this error

**Comment by sehilyi** [comment]
I think it is related to the visualization part, can you tell me which example resulted in the error?

#50

**Comment by wangqianwen0418** [comment]
Sometimes, the basic-linking-views has this problem

**Comment by wangqianwen0418** [comment]
image

Like this, but the problem not always happen

**Comment by sehilyi** [comment]
@wangqianwen0418 Thanks a lot for sharing this bug. 

I will need to investigate more, but I think rendering too many PIXI elements sometimes making such errors.

**Pull request merged**
