### PR TITLE
docs: update README.md

### LINKED ISSUE #155: Update README.md

### PR DESCRIPTION
**Pull request by wangqianwen0418**
@sehilyi , any comments are welcome!

Also, we might need to store the logos (with/without names, different ratios) in one place.

### CODE REVIEW

**Review by sehilyi — COMMENTED** [review]
Looks good, cool to see the GIF image! 

Since we are expecting to have more examples and resources very soon, let's keep this PR here for a while.

**Comment by sehilyi** [comment]
@wangqianwen0418, I've updated README.md just a bit for the readability (e.g., used table to show example code and GIF, restructured little). I also removed our logo for now as it doesn't look good in the GitHub dark mode as you had mentioned before.

But I think it is ready to go, and I think we will be able to update this a bit more before v0.7.

Please feel free to give feedback on the my update and/or merge this into master branch.

**Review by sehilyi — APPROVED** [review]

**Comment by sehilyi** [comment]
And yes, we will need to put png files in diverse sizes so that we can use that inside our editor and in other applications.

**Comment by wangqianwen0418** [comment]
@sehilyi , many thanks!

I have one concern about the table layout. I like the idea and have tried before.
But it is really hard to modify the width of the table cell. (Because cell are inline-display. I have also tried to change the style to block-display but it doesn't work)
Below is a screenshot from the updateReadme branch.
image

**Comment by wangqianwen0418** [comment]
For the logo, I think we can use the one I made for now? 
It has a white background so it will be okay (even though not prefect) for the dark mode.

**Comment by sehilyi** [comment]
I also confronted that issue, but I guess I underestimated it by assuming that people will likely see the `README.md` file more frequently on their desktops/laptops rather than mobile devices (which is not necessarily true).

We could reduce the width of the left code by removing the data URL and adding new lines:

Screen Shot 2021-02-03 at 2 25 56 PM

But the issue still exists when opening on the mobile (i.e., with narrower screen).

I used the table just because width of the code and the GIF is relatively small, and arranging them vertically would make the README.md needlessly longer.

However, I am on the fence now considering the mobile issue, so it's your call!

(We could later put another and more wider example that better represent the strength of our grammar.)

**Comment by sehilyi** [comment]
For the logo, I personally think that white rectangular boundary of the logo and black background of the document in a dark mode is making it not looking great. And I also prefer to have the title as a pure text.

**Comment by wangqianwen0418** [comment]
Cool, I like the way you modify the code part to reduce the width. 
Let's use the table layout!

**Comment by wangqianwen0418** [comment]
I am working on the data configuration part, so the example needs to update after that. I will merge the readme when the new example is ready.

**Comment by wangqianwen0418** [comment]
https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981
Seems there is not a good way to detect theme mode now

**Comment by sehilyi** [comment]
When you update the examples for `data/metadata` in the docs, could you please also update `visibility` options? Recently, I changed its type from `object` to `array of object` (#136), and if there is any example in docs that contains `visibility` options, it would not work properly. You just need to change `visibility: { ... }` to `visibility: [{ ... }]`.

https://github.com/gosling-lang/gosling.js/blob/9d166be53d848c318e58beada2aef910a1f13b19/src/core/gosling.schema.ts#L221

**Comment by wangqianwen0418** [comment]
> When you update the examples for `data/metadata` in the docs, could you please also update `visibility` options? Recently, I changed its type from `object` to `array of object` (#136), and if there is any example in docs that contains `visibility` options, it would not work properly. You just need to change `visibility: { ... }` to `visibility: [{ ... }]`.
> 

I am so sorry for missing this message! Please feel free to ping me at slack if something similar happen in the future

**Pull request merged**
